### ISSUE TITLE
 Function 'getHomeGeoPoint' called error

### ISSUE THREAD

**Issue by yujianyuanhaha** [AirSimDroneSimulator/AirSim#2]
when I run `main.py` of __DQN__, with the __disable__ of line `test_model = keras.models.load_model("finala.h5")` error is like
``` bash
Waiting for connection: Traceback (most recent call last):

  File "<ipython-input-3-b89e661141da>", line 1, in <module>
    runfile('/home/jet/AirSim/PythonClient/3D_path_finding/DQN/main.py', wdir='/home/jet/AirSim/PythonClient/3D_path_finding/DQN')

  File "/home/jet/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/jet/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/jet/AirSim/PythonClient/3D_path_finding/DQN/main.py", line 78, in <module>
    env = drone_env.drone_env_gridworld()

  File "/home/jet/AirSim/PythonClient/3D_path_finding/DQN/drone_env.py", line 55, in __init__
    drone_env.__init__(self,start,aim)

  File "/home/jet/AirSim/PythonClient/3D_path_finding/DQN/drone_env.py", line 14, in __init__
    self.client.confirmConnection()

  File "/home/jet/AirSim/PythonClient/3D_path_finding/DQN/AirSimClient.py", line 210, in confirmConnection
    home = self.getHomeGeoPoint()

  File "/home/jet/AirSim/PythonClient/3D_path_finding/DQN/AirSimClient.py", line 219, in getHomeGeoPoint
    return GeoPoint.from_msgpack(self.client.call('getHomeGeoPoint'))

  File "/home/jet/anaconda3/lib/python3.5/site-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()

  File "/home/jet/anaconda3/lib/python3.5/site-packages/msgpackrpc/future.py", line 45, in get
    raise error.RPCError(self._error)

RPCError: rpclib: client error C0002: Function 'getHomeGeoPoint' was called with an invalid number of arguments. Expected: 0, got: 1
```
The problem also happen when I run run `main.py` of __DDQN__ and `captureimages.py` of __Object_Detection/Faster_R-CNN__
anyway I can fix it? Thanks

**Comment by yujianyuanhaha** [comment]
I later find it is the version, this project is based on AirSim older version while I am on v1.2.0, refer to update api .md file for solutions.

**Comment by ConnLiu** [comment]
where is the updateapi.md, please?
