### ISSUE TITLE
When running , I met a question.

### ISSUE THREAD

**Issue by wearesunshines** [AirSimDroneSimulator/AirSim#6]
Waiting for connection: Traceback (most recent call last):
  File "C:/Users/DELL/Documents/GIT/AirSim-master/3D_path_finding/DDPG1/main.py", line 77, in <module>
    main()
  File "C:/Users/DELL/Documents/GIT/AirSim-master/3D_path_finding/DDPG1/main.py", line 22, in main
    env = drone_env_heightcontrol(aim = None)
  File "C:\Users\DELL\Documents\GIT\AirSim-master\3D_path_finding\DDPG1\drone_env.py", line 136, in __init__
    drone_env.__init__(self,start,aim)
  File "C:\Users\DELL\Documents\GIT\AirSim-master\3D_path_finding\DDPG1\drone_env.py", line 18, in __init__
    self.client.confirmConnection()
  File "C:\Users\DELL\Documents\GIT\AirSim-master\3D_path_finding\DDPG1\AirSimClient.py", line 210, in confirmConnection
    home = self.getHomeGeoPoint()
  File "C:\Users\DELL\Documents\GIT\AirSim-master\3D_path_finding\DDPG1\AirSimClient.py", line 219, in getHomeGeoPoint
    return GeoPoint.from_msgpack(self.client.call('getHomeGeoPoint'))
  File "C:\Users\DELL\PycharmProjects\AirSim-master\lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "C:\Users\DELL\PycharmProjects\AirSim-master\lib\site-packages\msgpackrpc\future.py", line 43, in get
    raise self._error
msgpackrpc.error.TransportError: Retry connection over the limit

What's wrong? Can anybody give me an advice.Many thanks!

**Comment by Wanglonghong222** [comment]
maybe you should add import airsim in drone_env.py

**Comment by wearesunshines** [comment]
&nbsp;
Hello,thanks.I have solved my problem. Your research is great and interesting.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wanglonghong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月9日(星期六) 下午3:08
收件人:&nbsp;"AirSimDroneSimulator/AirSim"<AirSim@noreply.github.com&gt;;
抄送:&nbsp;"魏文舒"<993469306@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AirSimDroneSimulator/AirSim] When running , I met a question. (#6)




maybe you should add import airsim in drone_env.py

**Comment by Wanglonghong222** [comment]
I want to ask, why is img here [64, 64, 3] instead of [64, 64, 1]




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wearesunshines"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月9日(星期六) 下午3:10
收件人:&nbsp;"AirSimDroneSimulator/AirSim"<AirSim@noreply.github.com&gt;;
抄送:&nbsp;"王隆洪"<442111482@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [AirSimDroneSimulator/AirSim] When running , I met a question. (#6)



&amp;nbsp; 
 Hello,thanks.I have solved my problem. Your research is great and interesting. 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Wanglonghong"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年11月9日(星期六) 下午3:08 
 收件人:&amp;nbsp;"AirSimDroneSimulator/AirSim"<AirSim@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"魏文舒"<993469306@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [AirSimDroneSimulator/AirSim] When running , I met a question. (#6) 
 
 
 
 
 maybe you should add import airsim in drone_env.py
