### ISSUE TITLE
When running the main.py form DDPG, there appears a problem.

### ISSUE THREAD

**Issue by Bourne98** [AirSimDroneSimulator/AirSim#7]
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-5
OMP: Info #214: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #156: KMP_AFFINITY: 6 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #285: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
OMP: Info #285: KMP_AFFINITY: topology layer "L3 cache" is equivalent to "socket".
OMP: Info #285: KMP_AFFINITY: topology layer "L2 cache" is equivalent to "core".
OMP: Info #285: KMP_AFFINITY: topology layer "L1 cache" is equivalent to "core".
OMP: Info #285: KMP_AFFINITY: topology layer "thread" is equivalent to "core".
OMP: Info #191: KMP_AFFINITY: 1 socket x 6 cores/socket x 1 thread/core (6 total cores)
OMP: Info #216: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to socket 0 core 1 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to socket 0 core 2 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to socket 0 core 3 
OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to socket 0 core 4 
OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to socket 0 core 5 
OMP: Info #252: KMP_AFFINITY: pid 10532 tid 10532 thread 0 bound to OS proc set 0
2021-04-22 11:32:25.447055: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "/home/bourne/RL_learning_code/AirSim-master/3D_path_finding/DDPG/main.py", line 77, in <module>
    main()
  File "/home/bourne/RL_learning_code/AirSim-master/3D_path_finding/DDPG/main.py", line 22, in main
    env = drone_env_heightcontrol(aim = None)
  File "/home/bourne/RL_learning_code/AirSim-master/3D_path_finding/DDPG/drone_env.py", line 136, in __init__
    drone_env.__init__(self,start,aim)
  File "/home/bourne/RL_learning_code/AirSim-master/3D_path_finding/DDPG/drone_env.py", line 18, in __init__
    self.client.confirmConnection()
  File "/home/bourne/RL_learning_code/AirSim-master/3D_path_finding/DDPG/AirSimClient.py", line 210, in confirmConnection
    home = self.getHomeGeoPoint()
  File "/home/bourne/RL_learning_code/AirSim-master/3D_path_finding/DDPG/AirSimClient.py", line 219, in getHomeGeoPoint
    return GeoPoint.from_msgpack(self.client.call('getHomeGeoPoint'))
  File "/home/bourne/anaconda3/envs/tensorflow1_cpu/lib/python3.7/site-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/home/bourne/anaconda3/envs/tensorflow1_cpu/lib/python3.7/site-packages/msgpackrpc/future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: client error C0002: Function 'getHomeGeoPoint' was called with an invalid number of arguments. Expected: 0, got: 1
Waiting for connection:

**Comment by Bourne98** [comment]
I successfully opened the environment and ran the client from Unreal Engine, but when runs this code, it fails.

**Comment by hunter55555** [comment]
have you solved  it，I met the same issue

**Comment by doom0831** [comment]
I met the same issue too, have anyone sloved it?
